config/routes.rb
Twitter::Application.routes.draw do
  resources :relationships

  resources :tweets

  get "sessions/new"
  get "log_out" => "sessions#destroy", :as => "log_out"

  get 'buddies', to: 'users#buddies', as: 'buddies'
  resources :users

  resources :sessions

  match 'user_show', :to => 'users#show'

   root :to => 'sessions#new'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  attr_accessible :followed_id, :follower_id
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  default_scope order: 'created_at DESC'
  attr_accessible :content, :userid
  belongs_to :user
 
  validates :content, length: { maximum: 160 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets

  has_many :follower_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followed_relationships, class_name: "Relationship", foreign_key: "follower_id"
  
  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships

  has_secure_password
  attr_accessible :email, :password_digest,:password, :password_confirmation,:user_name
  validates_uniqueness_of :email,:user_name
  validates_presence_of :email, :user_name
 ##validates_presence_of :email  



def following? user
    self.followeds.include? user
end
 
def follow user
    Relationship.create follower_id: self.id, followed_id: user.id
end

  


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

def authorize
  redirect_to login_url, alert: "Not authorized" if current_user.nil?
end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def create
        @relationship = Relationship.new
        @relationship.followed_id = params[:followed_id]
        @relationship.follower_id = current_user.id
 
    if @relationship.save
        redirect_to User.find params[:followed_id]
    else
        flash[:error] = "Couldn't Follow"
        redirect_to root_url
    end
end

def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to user_path(@relationship.followed_id)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to users_path, notice: "Logged in!"
  else
    flash.now.alert = "Email or password is invalid"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, notice: "Logged out!"
end



end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

def create
  @tweet = Tweet.new(params[:tweet])
  @tweet.user_id = current_user.id
 
  if @tweet.save
      redirect_to current_user
  else
      flash[:error] = "Problem!"
      redirect_to current_user
  end
end

def index
    @tweets = Tweet.all include: :user
    @tweet = Tweet.new
end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    #@user = User.new

   if current_user
        redirect_to buddies_path
    else
        @user = User.new
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @tweet = Tweet.new
    @relationship = Relationship.where(follower_id: current_user.id,followed_id: @user.id).first_or_initialize if current_user
    
  end

  def index
    @users = User.all
    
  end

  def buddies
    if current_user
        @tweet = Tweet.new
        buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
        @tweets = Tweet.find_all_by_user_id buddies_ids
    else
        redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header>
        <div class="wrapper">
            <img src="/assets/logo.png">
            <span>Twitter </span>
            <% if current_user %>
		<%= link_to "Public Tweets", tweets_path %>
                <%= link_to "Buddies' Tweets", buddies_path %>
                <%= link_to "Public Profiles", users_path %>
                <%= link_to "My Profile", current_user %>
		 Logged in as <%= current_user.email %>.
		  <%= link_to "Log Out", log_out_path %>
	     <% else %>
		  <%= link_to "Sign Up", new_user_path %> or
		  <%= link_to "Log In", new_session_path %>
	    <% end %>
        </div>
    </header>
<div id="user_nav">


</div>

    <div id="content">
        <div class="wrapper">
            <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, class: "flash #{name}" %>
            <% end %>
            <%= yield %>
        </div>
    </div>
    <footer>
        <div class="wrapper">
            
        </div>
    </footer>
</body>
</html>

app/views/tweets/index.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Tweet</h1>
    <p>
    <%= form_for @tweet do |f| %>
        <%= f.text_area :content, class: 'ribbitText' %>
        <%= f.submit "Tweet!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Public Tweets</h1>
    <% @tweets.each do |tweet| %>
        <div class="ribbitWrapper">
            <a href="<%= user_path tweet.user %>">
            <span class="name"><%= tweet.user.user_name %></span>
            </a>
            <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
            <p> <%= tweet.content %> </p>
        </div>
    <% end %>
</div>

app/views/users/buddies.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Tweet</h1>
    <p>
    <%= form_for @tweet do |f| %>
        <%= f.text_area :content, class: 'ribbitText', :rows => 8 %>
        <%= f.submit "Tweet!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Buddies' Tweets</h1>
    <% @tweets.each do |tweet| %>
        <div class="ribbitWrapper">
            <a href="<%= user_path tweet.user %>">
            <span class="name"><%= tweet.user.user_name %></span>
            </a>
            <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
            <p> <%= tweet.content %> </p>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<div id="ribbits" class="panel left">
    <h1>Public Profile</h1>
    <% @users.each do |user| %>
    <div class="ribbitWrapper">
        <a href="<%= user_path user %>">
        <span class="name"><%= user.user_name %></span>
        </a>
        
        <p>
        <%= user.tweets.size %> Tweets
        <span class="spacing"><%= user.followers.count %> Followers</span>
        <span class="spacing"><%= user.followeds.count %> Following</span>
        </p>
        <% if user.tweets.first %>
        <p><%= user.tweets.first.content %></p>
        <% end %>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<img src="/assets/frog.jpg">
<div class="panel right">
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name, 'Username' %><br />
    <%= f.text_field :user_name %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>
</div>

app/views/users/show.html.erb
<% if current_user %>
<div id="createRibbit" class="panel right">
    <h1>Create a Tweet</h1>
    <p>
    <%= form_for @tweet do |f| %>
        <%= f.text_area :content, class: 'ribbitText',:rows => 8 %>
        <%= f.submit "Tweet!" %>
    <% end %>
    </p>
</div>
<% end %>
<div id="ribbits" class="panel left">
    <h1>Your Profile</h1>
    <div class="ribbitWrapper">
       
        <span class="name"><%= @user.user_name %></span> 
        <p>
        
        <%= @user.tweets.size %> Tweets
        <span class="spacing"><%= @user.followers.count %> Followers</span>
        <span class="spacing"><%= @user.followeds.count %> Following</span>
        
        <% if current_user and @user != current_user %>
	    <% if current_user.following? @user %>
		<%= form_tag relationship_path(@relationship), method: :delete do %>
		    <%= submit_tag "Unfollow" %>
		<% end %>
	    <% else %>
		<%= form_for @relationship do %>
		    <%= hidden_field_tag :followed_id, @user.id %>
		    <%= submit_tag "Follow" %>
		<% end %>
	    <% end %>
        <% end %>

        </p>
    </div>
</div>
<div class="panel left">
    <h1>Your Tweets</h1>
    <% @user.tweets.each do |tweet| %>
        <div class="ribbitWrapper">
            
            <span class="name"><%= @user.user_name %></span>
            <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
            <p> <%= tweet.content %> </p>
        </div>
    <% end %>
</div